# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from chatbot_server.models.base_model_ import Model
from chatbot_server import util


class Answer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, answer: str=None):  # noqa: E501
        """Answer - a model defined in Swagger

        :param answer: The answer of this Answer.  # noqa: E501
        :type answer: str
        """
        self.swagger_types = {
            'answer': str
        }

        self.attribute_map = {
            'answer': 'answer'
        }

        self._answer = answer

    @classmethod
    def from_dict(cls, dikt) -> 'Answer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Answer of this Answer.  # noqa: E501
        :rtype: Answer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def answer(self) -> str:
        """Gets the answer of this Answer.


        :return: The answer of this Answer.
        :rtype: str
        """
        return self._answer

    @answer.setter
    def answer(self, answer: str):
        """Sets the answer of this Answer.


        :param answer: The answer of this Answer.
        :type answer: str
        """
        if answer is None:
            raise ValueError("Invalid value for `answer`, must not be `None`")  # noqa: E501

        self._answer = answer
