# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from chatbot_server.models.base_model_ import Model
from chatbot_server.models.training_questions import TrainingQuestions  # noqa: F401,E501
from chatbot_server import util


class TrainInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, created: datetime=None, training_data: List[TrainingQuestions]=None, finished: bool=None):  # noqa: E501
        """TrainInfo - a model defined in Swagger

        :param created: The created of this TrainInfo.  # noqa: E501
        :type created: datetime
        :param training_data: The training_data of this TrainInfo.  # noqa: E501
        :type training_data: List[TrainingQuestions]
        :param finished: The finished of this TrainInfo.  # noqa: E501
        :type finished: bool
        """
        self.swagger_types = {
            'created': datetime,
            'training_data': List[TrainingQuestions],
            'finished': bool
        }

        self.attribute_map = {
            'created': 'created',
            'training_data': 'trainingData',
            'finished': 'finished'
        }

        self._created = created
        self._training_data = training_data
        self._finished = finished

    @classmethod
    def from_dict(cls, dikt) -> 'TrainInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrainInfo of this TrainInfo.  # noqa: E501
        :rtype: TrainInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created(self) -> datetime:
        """Gets the created of this TrainInfo.


        :return: The created of this TrainInfo.
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created: datetime):
        """Sets the created of this TrainInfo.


        :param created: The created of this TrainInfo.
        :type created: datetime
        """

        self._created = created

    @property
    def training_data(self) -> List[TrainingQuestions]:
        """Gets the training_data of this TrainInfo.


        :return: The training_data of this TrainInfo.
        :rtype: List[TrainingQuestions]
        """
        return self._training_data

    @training_data.setter
    def training_data(self, training_data: List[TrainingQuestions]):
        """Sets the training_data of this TrainInfo.


        :param training_data: The training_data of this TrainInfo.
        :type training_data: List[TrainingQuestions]
        """

        self._training_data = training_data

    @property
    def finished(self) -> bool:
        """Gets the finished of this TrainInfo.


        :return: The finished of this TrainInfo.
        :rtype: bool
        """
        return self._finished

    @finished.setter
    def finished(self, finished: bool):
        """Sets the finished of this TrainInfo.


        :param finished: The finished of this TrainInfo.
        :type finished: bool
        """

        self._finished = finished
